### ISSUE TITLE
`NewType` wrapping an `Annotated` with constraints is unsupported

### ISSUE THREAD

**Issue by MaximZayats** [jcrist/msgspec#271]
Hi!
When I tried to use  `msgspec.json.schema` with `NewType` I got an error:

```python
from typing import NewType, Annotated

import msgspec

NewStr = NewType(
    "NewStr",
    Annotated[str, msgspec.Meta(extra_json_schema={"example": 10})],
)

print(msgspec.json.schema(NewStr))
```

```
Traceback (most recent call last):
  File "C:\Users\...\file.py", line 10, in <module>
    print(msgspec.json.schema(NewStr))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\venv\Lib\site-packages\msgspec\_json_schema.py", line 36, in schema
    (out,), components = schema_components((type,))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\venv\Lib\site-packages\msgspec\_json_schema.py", line 80, in schema_components
    schemas = tuple(_to_schema(t, name_map, ref_template) for t in type_infos)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\venv\Lib\site-packages\msgspec\_json_schema.py", line 80, in <genexpr>
    schemas = tuple(_to_schema(t, name_map, ref_template) for t in type_infos)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\venv\Lib\site-packages\msgspec\_json_schema.py", line 372, in _to_schema
    raise TypeError(
TypeError: Custom types currently require a schema be explicitly provided by annotating the type with `Meta(extra_json_schema=...)` - type typing.Annotated[str, msgspec.Meta(extra_json_schema={'example': 10})] is not supported
```

**Comment by jcrist** [comment]
Thanks for well written issue (and corresponding PR)!

This turns out to be a deeper issue than just enabling `msgspec.json.schema` support . We currently properly handle nested `NewType` declarations (e.g. `NewType("A", NewType("B",int))`), but don't handle `Annotated` wrappers *inside* a `NewType` (I didn't know this was allowed). This issue occurs in both the `msgspec.json.schema` handling as well as the `TypeNode` parsing functions in the c extension (the fiddliest bit of code in msgspec).

For now you can apply your annotations outside the `NewType` and everything works fine:

```python
from typing import NewType, Annotated

import msgspec

NewStr = Annotated[NewType("NewStr", str), msgspec.Meta(max_length=10)]

print("* JSON Schema")
print(msgspec.json.schema(NewStr))

print("* Encoding works")
print(msgspec.json.encode(NewStr("abcde")))

print("* Decoding works")
print(msgspec.json.decode(b'"abcde"', type=NewStr))

print("* Constraints are checked (this should error)")
msgspec.json.decode(b'"abcdefghijk"', type=NewStr)
```

Output:

```
* JSON Schema
{'type': 'string', 'maxLength': 10}
* Encoding works
b'"abcde"'
* Decoding works
abcde
* Constraints are checked (this should error)
Traceback (most recent call last):
  File "/home/jcristharif/Code/msgspec/test.py", line 17, in <module>
    msgspec.json.decode(b'"abcdefghijk"', type=NewStr)
msgspec.ValidationError: Expected `str` of length <= 10
```

Since this will require some deeper changes to the c extension, I'll need to take over your PR to finish it up. Should be able to resolve this issue before the next release.

**Comment by MaximZayats** [comment]
Hi, @jcrist!
Everything works as expected, thanks so much!

But, I have a question about nested `NewType` with the same `Meta` params:
```python
from typing import NewType, Annotated

import msgspec.json
from msgspec import Meta

A = NewType("A", Annotated[str, Meta(max_length=10)])
B = NewType("B", Annotated[A, Meta(max_length=20)])

print(msgspec.json.schema(B))
```

Currently it will raise an error:
```
TypeError: Multiple `Meta` annotations setting `max_length` found, type `__main__.B` is invalid
```

So, my question is:
Is it possible to override the `Meta` parameter ?
